# -*- coding: utf-8 -*-
"""ImageDifferencesnaturallanguage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4KaR6bEVg8Tx7_SH0hklxE6ksmtJ87W
"""

import google.generativeai as genai
import PIL.Image
import requests
from io import BytesIO
import base64

AIzaSyBJpbONpGYXl6s6VrwmTPLN83cEWhwXmIA

from google.colab import userdata
try:
    API_KEY = userdata.get('GEMINI_API_KEY')
except:
    print("Please set your GEMINI_API_KEY in Google Colab Secrets (left sidebar, padlock icon).")

genai.configure(api_key=API_KEY)

vision_model = genai.GenerativeModel('gemini-1.5-flash-latest')
llm_model = genai.GenerativeModel('gemini-1.5-flash-latest')

def load_image_from_local(image_path):
    """Loads an image from a local file path."""
    img = PIL.Image.open(image_path)
    return img

from google.colab import files
uploaded = files.upload() # This will open a file upload dialog
image_path_1 = list(uploaded.keys())[0]
image_1 = load_image_from_local(image_path_1)

from google.colab import files
uploaded = files.upload()
image_path_2 = list(uploaded.keys())[0]
image_2 = load_image_from_local(image_path_2)

print("\nAnalyzing Image 1...")
response1 = vision_model.generate_content(["Describe this image in detail, focusing on objects, colors, and overall scene.", image_1])
description1 = response1.text
print("Description of Image 1:\n", description1)

print("\nAnalyzing Image 1...")
response1 = vision_model.generate_content(["briefly Describe this image, focusing on objects, their position.", image_1])
description1 = response1.text
print("Description of Image 1:\n", description1)

rotated_image = image_1.rotate(-90, expand=True)

# --- Display the Rotated Image ---
print("\n--- Rotated Image (90 Degrees Clockwise) ---")
display(rotated_image.resize((300, 300))) #

print("\nAnalyzing Image 2...")
response2 = vision_model.generate_content(["briefly Describe this image, focusing on objects, their position.", image_2])
description2 = response2.text
print("Description of Image 2:\n", description2)
rotated_image = image_2.rotate(-90, expand=True)

# --- Display the Rotated Image ---
print("\n--- Rotated Image (90 Degrees Clockwise) ---")
display(rotated_image.resize((300, 300)))

from PIL import Image
import matplotlib.pyplot as plt
from IPython.display import display

# --- Rotate Images 90 Degrees Vertically (Clockwise) ---
# Rotating 90 degrees clockwise means using -90 or Image.ROTATE_90
rotated_image_1 = image_1.rotate(-90, expand=True)
rotated_image_2 = image_2.rotate(-90, expand=True)

# --- Display Rotated Images Side-by-Side ---
print("\n-- Images Side-by-Side ---")

# Create a figure and a set of subplots for displaying images
fig, axes = plt.subplots(1, 2, figsize=(10, 5)) # 1 row, 2 columns

# Display the first rotated image in the first subplot
axes[0].imshow(rotated_image_1)
axes[0].set_title('Image 1')
axes[0].axis('off') # Hide axes ticks and labels for cleaner display

# Display the second rotated image in the second subplot
axes[1].imshow(rotated_image_2)
axes[1].set_title('Image 2')
axes[1].axis('off') # Hide axes ticks and labels

# Adjust layout to prevent overlap
plt.tight_layout()

# Show the plot
plt.show()

print("\nComparing descriptions with the LLM...")
comparison_prompt = f"""
Image 1 Description:
{description1}

Image 2 Description:
{description2}

Based on the descriptions above, analyze the differences between Image 1 and Image 2, specifically focusing on any changes in the position or arrangement of objects between the two images. Highlight objects that have moved or are present in different locations. Be concise and clearly state the positional changes.summarize the difference
"""

llm_response = llm_model.generate_content(comparison_prompt)
comparison_result = llm_response.text

print("\n--- LLM's Comparison Result ---")
print(comparison_result)

from PIL import Image
import matplotlib.pyplot as plt
from IPython.display import display

# --- Rotate Images 90 Degrees Vertically (Clockwise) ---
# Rotating 90 degrees clockwise means using -90 or Image.ROTATE_90
# expand=True ensures the image size adjusts to fit the rotated content, preventing cropping.
rotated_image_1 = image_1.rotate(-90, expand=True)
rotated_image_2 = image_2.rotate(-90, expand=True)

# --- Display Rotated Images Side-by-Side ---
print("\n-- Images Side-by-Side ---")

# Create a figure and a set of subplots for displaying images
fig, axes = plt.subplots(1, 2, figsize=(10, 5)) # 1 row, 2 columns

# Display the first rotated image in the first subplot
axes[0].imshow(rotated_image_1)
axes[0].set_title('Image 1')
axes[0].axis('off') # Hide axes ticks and labels for cleaner display

# Display the second rotated image in the second subplot
axes[1].imshow(rotated_image_2)
axes[1].set_title('Image 2')
axes[1].axis('off') # Hide axes ticks and labels

# Adjust layout to prevent overlap
plt.tight_layout()

# Show the plot
plt.show()

from PIL import Image
import matplotlib.pyplot as plt
from IPython.display import display

# --- Rotate Images 90 Degrees Vertically (Clockwise) ---
# Rotating 90 degrees clockwise means using -90 or Image.ROTATE_90
# expand=True ensures the image size adjusts to fit the rotated content, preventing cropping.
rotated_image_1 = image_1.rotate(-90, expand=True)
rotated_image_2 = image_2.rotate(-90, expand=True)

# --- Display Rotated Images Side-by-Side ---
print("\n-- Images Side-by-Side ---")

# Create a figure and a set of subplots for displaying images
fig, axes = plt.subplots(1, 2, figsize=(10, 5)) # 1 row, 2 columns

# Display the first rotated image in the first subplot
axes[0].imshow(rotated_image_1)
axes[0].set_title('Image 1')
axes[0].axis('off') # Hide axes ticks and labels for cleaner display

# Display the second rotated image in the second subplot
axes[1].imshow(rotated_image_2)
axes[1].set_title('Image 2')
axes[1].axis('off') # Hide axes ticks and labels

# Adjust layout to prevent overlap
plt.tight_layout()

# Show the plot
plt.show()